version: "3.3"

services:
  bytebase:
    image: bytebase/bytebase:1.17.0
    restart: always
    ports:
      - "172.17.0.1:8458:8080"
    volumes:
      - ./data:/var/opt/bytebase
    command: --data /var/opt/bytebase --external-url https://${DOMAIN} --port 8080

  employee-prod:
    image: bytebase/sample-database:mysql-employee-small
    ports:
      - 172.17.0.1:3406:3306

  employee-test:
    image: bytebase/sample-database:mysql-employee-small
    ports:
      - 172.17.0.1:3407:3306