version: "3.3"

services:
  bytebase:
    image: bytebase/bytebase:1.17.0
    restart: always
    ports:
      - "172.17.0.1:8458:8080"
    volumes:
      - ./data:/var/opt/bytebase
    command: --data /var/opt/bytebase --external-url https://bytebase.example.com --port 8080